app:
  database:
    host: 127.0.0.1
    port: 3306
    user: admin
    name: fuyu_mes
    password: wAYabEqNxeF9c5Sq
    type: mysql
  servicePoint: tcp://127.0.0.1:23568
  componentTable: iot_component
  moduleName: "iot"
  loadComponentSchema: false
  enableMigration: false