app:
  database:
    host: 127.0.0.1
    port: 3306
    user: cerexio_admin
    name: fuyu_mes
    password: wAYabEqNxeF9c5Sq
    type: mysql
  recordTrailTable: energy_management_record_trail
  files:
    downloadDirectory: /tmp/energy_management
    uploadUrl: https://locahost/api/content/component/content_master/records
  servicePoint: tcp://127.0.0.1:23568
  componentTable: energy_management_component
  moduleName: "energy_management"
  excludeRoutingList:
    - 'GET,overview'
  enableMigration: false
  loadComponentSchema: false

